
d0 = [{"apples":1, "oranges":1, "labels":0 }, 
      {"apples":1, "oranges":1, "labels":1 }];

d1 = [{"apples":0, "oranges":1, "labels":0}, 
      {"apples":0, "oranges":1, "labels":0},
      {"apples":1, "oranges":1, "labels":1}, 
      {"apples":1, "oranges":1, "labels":1}];

d2 = [{"apples":0, "oranges":1}, 
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1}, 
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1}, 
      {"apples":0, "oranges":1},
      {"apples":1, "oranges":1}, 
      {"apples":1, "oranges":1}];

d33 = [{"apples":0, "oranges":1}, 
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1}, 
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1}, 
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1}, 
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":1, "oranges":1},
      {"apples":1, "oranges":1}];


d4 = [{"apples":0, "oranges":1}, 
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1}, 
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1}, 
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1}, 
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":1, "oranges":1},
      {"apples":1, "oranges":1}];


d5 = [{"apples":0, "oranges":1}, 
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1}, 
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1}, 
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1}, 
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":0, "oranges":1},
      {"apples":1, "oranges":1},
      {"apples":1, "oranges":1}];




